/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#3e4660",
        "secondary": "#4e616a",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "primary-container": "#131a33",
        "surface-variant": "#e0e3e5",
        "surface-container": "#eceef0",
        "tertiary-container": "#161c21",
        "surface": "#f7f9fb",
        "on-surface": "#191c1e",
        "on-secondary-fixed": "#0a1e25",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed": "#dde3ea",
        "tertiary-fixed-dim": "#c1c7ce",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#bec5e5",
        "on-tertiary-container": "#7e858b",
        "on-secondary-fixed-variant": "#374a51",
        "outline": "#76767e",
        "primary": "#000000",
        "secondary-container": "#cee3ed",
        "on-background": "#191c1e",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed-variant": "#41484d",
        "inverse-primary": "#bec5e5",
        "secondary-fixed-dim": "#b5cad3",
        "background": "#f7f9fb",
        "on-tertiary-fixed": "#161c21",
        "on-surface-variant": "#45464d",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d1e6ef",
        "outline-variant": "#c6c6ce",
        "on-primary-fixed": "#131a33",
        "surface-dim": "#d8dadc",
        "on-primary-container": "#7b83a0",
        "surface-container-highest": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "surface-tint": "#565d79",
        "on-secondary-container": "#52666e",
        "tertiary": "#000000"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "margin-mobile": "16px",
        "base": "8px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "section-gap": "120px"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}